version: "3.8"
services:
  ocrbot:
    build: .
    restart: unless-stopped
    command: "bash -c 'mount'"
    tmpfs: 
      - /home/OCRBOT/ramdisk
    volumes:
      - ./pythonfiles/:/home/OCRBOT/pythonfiles/
      - ./db/:/home/OCRBOT/db/
      - ./secrets/:/home/OCRBOT/secrets/
    command: bash -c "python3 -u ./pythonfiles/main.py"